-- -*- lua -*-
-- Module file created by spack (https://github.com/spack/spack) on 2019-09-16 14:16:12.240050
--
-- ninja@1.8.2%gcc@7.2.0 arch=linux-centos7-x86_64 /m2t3vgb
--

whatis([[Name : ninja]])
whatis([[Version : 1.8.2]])
whatis([[Short description : Ninja is a small build system with a focus on speed. It differs from other build systems in two major respects: it is designed to have its input files generated by a higher-level build system, and it is designed to run builds as fast as possible.]])

help([[Ninja is a small build system with a focus on speed. It differs from
other build systems in two major respects: it is designed to have its
input files generated by a higher-level build system, and it is designed
to run builds as fast as possible.]])



prepend_path("PATH", "/u/local/spack/0.12/opt/spack/linux-centos7-x86_64/gcc-7.2.0/ninja-1.8.2-m2t3vgb66hex24gfvh356natsvkd7hkg/bin", ":")
prepend_path("CMAKE_PREFIX_PATH", "/u/local/spack/0.12/opt/spack/linux-centos7-x86_64/gcc-7.2.0/ninja-1.8.2-m2t3vgb66hex24gfvh356natsvkd7hkg/", ":")
setenv("NINJA_ROOT", "/u/local/spack/0.12/opt/spack/linux-centos7-x86_64/gcc-7.2.0/ninja-1.8.2-m2t3vgb66hex24gfvh356natsvkd7hkg")

